export const texts = [
  "My XML monitor is down, our only choice is to parse and reboot the visual driver!",
  "My secretary accidentally tore up my presentation, so I couldn't send my research!",
  "You can't transcode the hard drive without synthesizing the auxiliary RSS application!",
  "My ASCII transistor is down, our only choice is to input and override the high speed bus!",
  "The SDRAM system is down, encode the 56k feed so we can connect the ASCII mainframe!",
  "My grandpa fatally swallowed my poster, so I couldn't sign off on my paper!",
  "Use the optical GB microchip, then you can shut down the virtual monitor!",
  "Injecting the hard drive won't do anything, we need to parse the cross-platform PHP capacitor!",
  "I want to contribute to my thesis, but my CIA contact said my cat purposely tore up it!",
  "They're inside the network, use the unicode Y2K alarm to calculate their pixel!",
  "Remember when my dog sat on my report? Well, today they unwittingly ruined it too, so I can't print it.",
  "They're inside the array, use the back-end SDRAM microchip to reboot their network!",
  "If we shut down the program, we can get to the VGA pixel through the solid state SDRAM alarm!",
  "Transmitting the capacitor won't do anything, we need to shut down the wireless SMTP array!",
  "They're inside the hard drive, use the back-end XML antenna to generate their system!",
];
